CREATE TABLE [dbo].[qf_inBill_billid](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[billid] [int] NULL,
 CONSTRAINT [PK_qf_inBill_billid] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

GO
